---
vagrantfile-local:
    vm:
        box: puphpet/debian75-x64
        box_url: puphpet/debian75-x64
        hostname: ''
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                wLqLfVijhCPo:
                    host: '8937'
                    guest: '22'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            mdbPyuLUGofW:
                source: ../../www
                target: /srv/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
            iu9W8zAGranl:
                source: ../../drush
                target: /etc/drush
                sync_type: nfs
                rsync:
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages: {  }
firewall:
    install: '1'
    rules: null
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    vhosts:
        rGTwR0cKVC7l:
            server_name: d7.drupal.dev
            www_root: /srv/www/d7
            listen_port: '80'
            location: \.php$
            index_files:
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - gd
            - intl
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        mbstring.http_input: pass
        mbstring.http_output: pass
    timezone: Europe/Moscow
    mod_php: 0
drush:
    install: '1'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        23EzvI0ULU1z:
            version: ''
python:
    install: '1'
    packages: {  }
    versions:
        Sex1PkMZFZQ1:
            version: ''
mysql:
    install: '1'
    root_password: root
    adminer: '1'
    databases:
        nqxFxrDzacpu:
            grant:
                - ALL
            name: d7
            host: localhost
            user: d7
            password: d7
            sql_file: ''
